/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yy_opencv_OpenCVProcessor */

#ifndef _Included_com_yy_opencv_OpenCVProcessor
#define _Included_com_yy_opencv_OpenCVProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yy_opencv_OpenCVProcessor
 * Method:    detectHoughCircles
 * Signature: (Ljava/lang/Object;IIII)[Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_yy_opencv_OpenCVProcessor_detectHoughCircles
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
